### ISSUE TITLE
Lombok annotation handler class lombok.eclipse.handlers.HandleExtensionMethod failed 

### ISSUE THREAD

**Issue by ViselnikAscet** [Mechanical-Advantage/RobotCode2024#25]
# I can't build
Hi
When I want to build the robot code, I get the Lombok annotation handlers class lombok.eclipse.handlers.HandleExtensionMethod error in the robotstate section, can you help?
<img width="821" alt="Ekran Resmi 2024-02-17 10 52 03" src="https://github.com/Mechanical-Advantage/RobotCode2024/assets/80203023/c80efb59-5677-44f4-a704-d8923f585b2a">

**Comment by ViselnikAscet** [comment]
> # I can't build
> Hi When I want to build the robot code, I get the Lombok annotation handlers class lombok.eclipse.handlers.HandleExtensionMethod error in the robotstate section, can you help? <img alt="Ekran Resmi 2024-02-17 10 52 03" width="821" src="https://private-user-images.githubusercontent.com/80203023/305611143-c80efb59-5677-44f4-a704-d8923f585b2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTY2NjYsIm5iZiI6MTcwODE1NjM2NiwicGF0aCI6Ii84MDIwMzAyMy8zMDU2MTExNDMtYzgwZWZiNTktNTY3Ny00NGY0LWE3MDQtZDg5MjNmNTg1YjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA3NTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNWQzYTJiZjFjYzQ3MWM2MzMzOWM2OTliNTc1M2I1M2QxYTUwNjFiZWUxMWFmMGVkYmFiYWMzZDEwNjNiOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KlKN3vyDW0liHf-MhCklsukwPs1_PGJNFC5kfWg4xS8">

And I am getting a configure static import error in some lines.

**Comment by jwbonner** [comment]
Keep in mind that we do not guarantee support for those outside the team to be able to build and run our robot code. Things are evolving quickly so this is just not within our capacity to support, though you are welcome of course to copy and use parts of the code with appropriate credit.

I would recommend trying to build the code regardless of any errors in VSCode, and then running "Java: Clean Java Language Server Workspace" from the command palette. Keep in mind that you will also need to build and run the trajectory generation gRPC service using Docker, or pass the environment variable `GENERATE_EMPTY_DRIVE_TRAJECTORIES=true` while building to disable trajectory generation entirely.

I'm going to close this issue since we won't be able to provide additional debugging support. If you have more general questions about the code, I encourage you to ask on our Open Alliance [build thread](https://www.chiefdelphi.com/t/frc-6328-mechanical-advantage-2024-build-thread/442736?u=jonahb55).
